[package]
name = "kernel-store"
version = "0.5.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
aes-gcm = "=0.10.3"
argon2 = "=0.5.3"
async-trait.workspace = true
etcd-client = { version = "=0.19.0", features = ["tls"] }
kernel-api = { version = "0.5.0", path = "../api" }
sha2 = "=0.10.9"
test-util = { version = "=0.4.5", package = "tokio-test", optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "macros", "rt", "time"] }
zeroize = { version = "=1.9.0", features = ["derive"] }

[lints]
workspace = true

[features]
test-util = ["dep:test-util"]
