[package]
name = "kernel-store"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
kernel-api = { version = "0.1.0", path = "../api" }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "macros", "rt", "time"] }

[lints]
workspace = true
