[package]
name = "kernel-store"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
aes-gcm.workspace = true
argon2.workspace = true
async-trait.workspace = true
etcd-client = { workspace = true, features = ["tls"] }
kernel-api = { version = "0.1.0", path = "../api" }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
sha2.workspace = true
tokio-test = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "macros", "rt", "time"] }
zeroize = { workspace = true, features = ["derive"] }

[lints]
workspace = true

[features]
test-util = ["dep:serde", "dep:serde_json", "dep:tokio-test"]
