[package]
name = "kernel-api"
version = "0.6.23"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
hex.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zeroize = { workspace = true, features = ["derive"] }

[lints]
workspace = true

[dev-dependencies]
insta = { workspace = true, features = ["json"] }
