[package]
name = "deployment"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
kernel-api = { path = "../../kernel/api" }
kernel-controller = { version = "0.1.0", path = "../../kernel/controller" }
kernel-store = { version = "0.1.0", path = "../../kernel/store" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
tokio.workspace = true
