FROM rust:1.97.0-alpine AS builder
RUN apk add --no-cache musl-dev protoc cmake make perl gcc g++
ENV CXXFLAGS=-g0
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY controller/Cargo.toml controller/Cargo.toml
COPY controller/src/ controller/src/
RUN cargo build --release --locked

FROM gcr.io/distroless/static-debian12
COPY --from=builder /app/target/release/maestro /maestro
ENTRYPOINT ["/maestro", "daemon", "probe"]
