[package]
name = "runtime"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "=0.1.89"
docker = { version = "=0.21.0", package = "bollard", optional = true }
futures-util = "=0.3.33"
hex = "=0.4.3"
kernel-api = { version = "0.1.0", path = "../kernel/api" }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.151"
sha2 = "=0.10.9"
supervisor = { version = "0.1.0", path = "../kernel/supervisor" }
test-util = { version = "=0.12.5", package = "parking_lot", optional = true }
thiserror = "=2.0.18"
time = { version = "=0.3.53", features = ["parsing"] }
tokio = { version = "=1.52.3", features = ["io-util", "macros", "rt", "sync", "time"] }

[lints]
workspace = true

[features]
test-util = ["dep:test-util"]
docker = ["dep:docker"]

[dev-dependencies]
tempfile = "=3.27.0"
test-util = { version = "=0.12.5", package = "parking_lot" }
tokio = { version = "=1.52.3", features = ["macros", "rt"] }
