[package]
name = "runtime"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "=0.1.89"
kernel-api = { version = "0.1.0", path = "../kernel/api" }
serde = { version = "=1.0.228", features = ["derive"] }
thiserror = "=2.0.18"
tokio = { version = "=1.52.3", features = ["sync"] }

[lints]
workspace = true

[dev-dependencies]
serde_json = "=1.0.151"
