[package]
name = "maestro-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "maestro"
path = "src/main.rs"

[dependencies]
aws-config = { workspace = true, features = [
  "credentials-login",
  "credentials-process",
  "default-https-client",
  "rt-tokio",
  "sso"
] }
aws-sdk-secretsmanager.workspace = true
clap.workspace = true
cluster = { version = "0.1.0", path = "../../cluster" }
crossterm.workspace = true
futures-util.workspace = true
flate2.workspace = true
ignore.workspace = true
jsonwebtoken.workspace = true
json5.workspace = true
ipnet.workspace = true
kernel-api = { path = "../../kernel/api" }
libc.workspace = true
logs = { version = "0.1.0", path = "../../observability/logs" }
reqwest = { workspace = true, features = ["json"] }
rpassword.workspace = true
rustls = { workspace = true, default-features = false, features = ["ring", "std"] }
semver.workspace = true
serde.workspace = true
serde_ignored.workspace = true
serde_path_to_error.workspace = true
serde_json.workspace = true
sha2.workspace = true
shellexpand.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tar.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "macros", "rt", "time"] }
tokio-tungstenite = { workspace = true, default-features = false, features = [
  "connect",
  "handshake",
  "rustls-tls-webpki-roots"
] }
uuid.workspace = true
webpki-roots.workspace = true
time.workspace = true
kernel-store = { version = "0.1.0", path = "../../kernel/store" }
base64.workspace = true

[lints]
workspace = true
