[package]
name = "node-fabric"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
kernel-api = { version = "0.1.0", path = "../../kernel/api" }
opentelemetry-proto = { version = "=0.32.0", default-features = false, features = ["gen-tonic", "trace", "logs", "metrics"] }
prost = "=0.14.4"
subtle = "=2.6.1"
thiserror.workspace = true
tonic = "=0.14.6"
tonic-prost = "=0.14.6"
zeroize = { version = "=1.9.0", features = ["derive"] }

[lints]
workspace = true

[build-dependencies]
tonic-prost-build = "=0.14.6"
