[package]
name = "node-fabric"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
kernel-api = { path = "../../kernel/api" }
opentelemetry-proto = { workspace = true, default-features = false, features = [
  "gen-tonic",
  "trace",
  "logs",
  "metrics"
] }
prost.workspace = true
subtle.workspace = true
thiserror.workspace = true
tonic = { workspace = true, features = ["codegen", "router", "transport"] }
tonic-prost.workspace = true
zeroize = { workspace = true, features = ["derive"] }

[lints]
workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
