[package]
name = "metrics"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
test-util = []

[dependencies]
async-trait.workspace = true
kernel-api = { version = "0.1.0", path = "../../kernel/api" }
node-agent = { version = "0.1.0", path = "../../node/agent" }
reqwest.workspace = true
runtime = { version = "0.1.0", path = "../../runtime", default-features = false }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }

[dev-dependencies]

[lints]
workspace = true
