[package]
name = "scheduler"
version = "0.6.1"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
kernel-api = { version = "0.6.1", path = "../../kernel/api" }
kernel-controller = { version = "0.6.1", path = "../../kernel/controller" }
kernel-store = { version = "0.6.1", path = "../../kernel/store" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
