[package]
name = "daemon"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
macos-platform = ["runtime/docker"]
test-util = ["kernel-controller/test-util", "kernel-store/test-util"]

[dependencies]
async-trait.workspace = true
aws-config = { workspace = true, default-features = false, features = [
  "default-https-client",
  "rt-tokio"
] }
aws-sdk-s3 = { workspace = true, default-features = false, features = [
  "default-https-client",
  "http-1x",
  "rt-tokio",
  "sigv4a"
] }
base64.workspace = true
chrono.workspace = true
clap.workspace = true
cluster = { version = "0.1.0", path = "../../cluster" }
build = { version = "0.1.0", path = "../../operators/build" }
deployment = { version = "0.1.0", path = "../../operators/deployment" }
dns = { version = "0.1.0", path = "../../operators/dns" }
firewall = { version = "0.1.0", path = "../../operators/firewall" }
futures-util.workspace = true
ingress = { version = "0.1.0", path = "../../operators/ingress" }
kernel-api = { path = "../../kernel/api" }
kernel-controller = { version = "0.1.0", path = "../../kernel/controller" }
kernel-store = { version = "0.1.0", path = "../../kernel/store" }
logs = { version = "0.1.0", path = "../../observability/logs" }
logstore = { version = "0.1.0", path = "../../observability/logstore" }
metrics = { version = "0.1.0", path = "../../observability/metrics" }
node-agent = { version = "0.1.0", path = "../../node/agent" }
preview = { version = "0.1.0", path = "../../operators/preview" }
runtime = { version = "0.1.0", path = "../../runtime", default-features = false }
scheduler = { version = "0.1.0", path = "../../operators/scheduler" }
semver.workspace = true
server = { version = "0.1.0", path = "../server" }
upgrade = { version = "0.1.0", path = "../../operators/upgrade" }
webhook = { version = "0.1.0", path = "../../operators/webhook" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
  "fs",
  "io-std",
  "io-util",
  "macros",
  "rt",
  "signal",
  "sync",
  "time"
] }
tracing.workspace = true
tracing-subscriber.workspace = true
maestro-cli = { version = "0.1.0", path = "../cli" }

[lints]
workspace = true

[dev-dependencies]
clustertest = { version = "0.1.0", path = "../../clustertest" }
insta = { workspace = true, features = ["redactions", "yaml"] }
jsonwebtoken.workspace = true
kernel-store = { version = "0.1.0", path = "../../kernel/store", features = ["test-util"] }
logs = { version = "0.1.0", path = "../../observability/logs", features = ["test-util"] }
metrics = { version = "0.1.0", path = "../../observability/metrics", features = ["test-util"] }
reqwest.workspace = true
rcgen = { workspace = true, features = ["pem"] }
runtime = { version = "0.1.0", path = "../../runtime", default-features = false, features = [
  "test-util"
] }
time.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "time"] }
tokio-tungstenite = { workspace = true, default-features = false, features = [
  "connect",
  "handshake"
] }

[target.'cfg(target_os = "linux")'.dependencies]
runtime = { version = "0.1.0", path = "../../runtime", default-features = false, features = [
  "containerd"
] }

[target.'cfg(target_os = "macos")'.dependencies]
runtime = { version = "0.1.0", path = "../../runtime", default-features = false, features = [
  "docker"
] }
