[package]
name = "kernel-controller"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
kernel-api = { version = "0.1.0", path = "../api" }
kernel-store = { version = "0.1.0", path = "../store" }
serde.workspace = true
serde_json = "=1.0.151"
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
