#![allow(clippy::unwrap_used, clippy::expect_used)]

mod affinity;
mod build;
mod cluster_setup;
mod election;
mod formation;
mod lifecycle;
mod lifecycle_control;
mod lifecycle_sequence;
mod lifecycle_stress;
mod preview;
mod quorum;
mod restart;
mod rollout;
mod routing;
mod scheduling;
mod smoke;
mod upgrade;
