#!/usr/bin/env python3
"""Enforce mechanical Rust source-layout rules from GUIDE.md."""

from __future__ import annotations

from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent.parent
CRATES = ROOT / "crates"
MANDATORY_SPLIT_LINES = 800
DECLARATION = re.compile(
    r"(?:pub(?:\([^)]*\))?\s+)?(?:"
    r"mod\s+[A-Za-z_][A-Za-z0-9_]*"
    r"|use\s+.+"
    r"|type\s+[A-Za-z_][A-Za-z0-9_]*(?:<.+>)?\s*=\s*.+"
    r");",
    re.DOTALL,
)


def generated_source(text: str) -> bool:
    header = "\n".join(text.splitlines()[:8]).lower()
    return "@generated" in header or "generated by" in header or "do not edit" in header


def declaration_only(text: str) -> bool:
    statement = ""
    in_block_comment = False
    attribute_depth = 0

    for source_line in text.splitlines():
        line = source_line.strip()
        if attribute_depth:
            attribute_depth += line.count("[") - line.count("]")
            if attribute_depth <= 0:
                attribute_depth = 0
            continue
        if in_block_comment:
            if "*/" in line:
                line = line.split("*/", 1)[1].strip()
                in_block_comment = False
            else:
                continue
        if line.startswith("/*"):
            if "*/" in line:
                line = line.split("*/", 1)[1].strip()
            else:
                in_block_comment = True
                continue
        if not line or line.startswith("//"):
            continue
        if line.startswith("#[") or line.startswith("#!["):
            attribute_depth = line.count("[") - line.count("]")
            continue
        if "//" in line:
            line = line.split("//", 1)[0].rstrip()
        statement = f"{statement} {line}".strip()
        if statement.endswith(";"):
            if DECLARATION.fullmatch(statement) is None:
                return False
            statement = ""

    return not in_block_comment and attribute_depth == 0 and not statement


def embedded_test_module(path: Path, text: str) -> bool:
    relative = path.relative_to(CRATES)
    parts = relative.parts
    try:
        source_index = parts.index("src")
    except ValueError:
        return False
    source_parts = parts[source_index + 1 :]
    return (
        path.name != "lib.rs"
        and "tests" not in source_parts[:-1]
        and "#[cfg(test)]" in text
    )


def main() -> int:
    failures: list[str] = []
    sources = sorted(CRATES.rglob("*.rs"))

    for path in sources:
        text = path.read_text(encoding="utf-8")
        relative = path.relative_to(ROOT)
        line_count = len(text.splitlines())
        if line_count >= MANDATORY_SPLIT_LINES and not generated_source(text):
            failures.append(
                f"{relative}: {line_count} lines exceeds the mandatory split threshold"
            )
        if path.name == "mod.rs" and not declaration_only(text):
            failures.append(f"{relative}: mod.rs may contain only declarations and re-exports")
        if path.name == "lib.rs" and not declaration_only(text):
            failures.append(
                f"{relative}: lib.rs may contain only declarations, re-exports, and type aliases"
            )
        if embedded_test_module(path, text):
            failures.append(
                f"{relative}: move #[cfg(test)] coverage into the mirrored src/tests tree"
            )

    if failures:
        print("source layout violations:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1

    print(f"checked {len(sources)} Rust source files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
