[package]
name = "controller"
version = "0.3.10"
edition = "2024"
rust-version = "1.97.0"

[[bin]]
name = "maestro"
path = "src/main.rs"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.103"
argon2 = "0.5.3"
async-trait = "0.1"
axum = { version = "0.8", features = ["multipart"] }
http-body-util = "0.1"
backon = "1.6.0"
base64 = "0.22"
chrono = "0.4"
chacha20poly1305 = "0.11.0"
clap = { version = "4.5", features = ["derive", "env"] }
etcd-client = { version = "0.19", features = ["tls"] }
flume = "0.12.0"
flate2 = "1.1"
hex = "0.4.3"
hkdf = "0.12.4"
hmac = "0.12.1"
json5 = "0.4"
libc = "0.2"
nanoid = "0.4"
os_pipe = "1"
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "multipart",
  "stream",
  "rustls-tls"
] }
rusqlite = { version = "0.39.0", features = ["bundled"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_ignored = "0.1.14"
serde_json = "1.0"
serde_json_canonicalizer = "0.3.2"
serde_path_to_error = "0.1.20"
semver = "1.0"
sha2 = "0.10"
shellexpand = "3.1.2"
strip-ansi-escapes = "0.2"
sysinfo = "0.38.4"
tokio = { version = "1.48", features = [
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
  "fs",
  "io-util"
] }
tokio-util = { version = "0.7", features = ["io"] }
watchexec-supervisor = "4.0"
x25519-dalek = { version = "3.0.0", features = ["getrandom", "static_secrets"] }
zeroize = { version = "1.8.2", features = ["derive"] }
aws-sdk-secretsmanager = { version = "1.109.0", default-features = false, features = [
  "default-https-client",
  "rt-tokio"
] }
aws-config = { version = "1.9.0", features = ["credentials-login"] }
jsonwebtoken = { version = "10.4.0", default-features = false, features = ["aws_lc_rs"] }
rcgen = { version = "0.14.7", features = ["pem"] }
rustls = { version = "0.23.37", features = ["ring"] }
dotenvy = "0.15.7"
rpassword = "7.5.2"
inquire = "0.9.4"
regex = "1.12.3"
tar = "0.4.46"
ignore = "0.4.25"
r2d2 = "0.8.10"
r2d2_sqlite = "0.34.0"
duckdb = { version = "=1.4.1", features = ["bundled", "json", "parquet"] }
aws-sdk-s3 = { version = "1.138.0", default-features = false, features = [
  "sigv4a",
  "http-1x",
  "default-https-client",
  "rt-tokio"
] }
axum-server = { version = "0.8.0", features = ["tls-rustls-no-provider"] }

[dev-dependencies]
proptest = "1.11.0"
